WebScraping/urls.py
from django.contrib import admin
from django.urls import path, include
from repositorios import urls
from repositorios import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('repositorios/', include(('repositorios.urls','app_name'), namespace='repositorios')),
    path('buscar_repositorios/', views.buscar_repositorios),
    path('buscar/', views.buscar),
]

#include('repositorios.urls', namespace='repositorios', app_name='repositorios')),

repositorios/urls.py
from django.urls import path
from repositorios import views

urlpatterns = [
    path('index_repositorios/', views.list_repositorio, name='index_repositorios'),
    path('create_user/', views.UserCreate.as_view(), name='create_user'),
    #path('buscar_git/', views.buscar_repositorios.as_view(), name='buscar_git'),
]

repositorios/models.py
from django.db import models
from django.contrib.auth.hashers import make_password

# Create your modelmodels.Model.

class Usuario(models.Model):
    nombre=models.CharField(max_length=50)
    apellido=models.CharField(max_length=50)
    email=models.EmailField()
    password=models.CharField(max_length=32)

class Repositorio(models.Model):
    titulo=models.CharField(max_length=500, null=True)
    descripcion=models.CharField(max_length=500, null=True)
    #watch=models.CharField(max_length=20, null=True)
    star=models.IntegerField(null=True)
    fork=models.IntegerField(null=True)
    fecha_creacion = models.DateField(max_length=100, null=True)
    fecha_actualizacion = models.CharField(max_length=100, null=True)
    url_commits = models.CharField(max_length=500, null=True)
    url_colaboradores=models.CharField(max_length=500, null=True)
    url_lenguajes = models.CharField(max_length=500, null=True)
    url_repositorio=models.CharField(max_length=500, null=True)

repositorios/views.py
from django.urls import reverse
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView
from repositorios.createUser import UserForm
from django.views.generic.list import ListView
from django.http import HttpResponse

from repositorios.models import Usuario, Repositorio


# Create your views here.

def list_repositorio(request):
	repositorio = Repositorio.objects.all()
	return render(request, template_name='index_repositorios.html', context={'repositorio':repositorio})



class UserCreate(CreateView):
	model = Usuario
	form_class = UserForm
	template_name = 'add_user.html'

	def get_success_url(self):
		return reverse('repositorios:index_repositorios')

def buscar_repositorios(request):
	return render(request, "buscar_repositorio.html")

def buscar(request):
	mensaje = "Repositorio buscado: %r" % request.GET['git']
	return HttpResponse(mensaje)

WebScraping/templates/add_user.html
{% extends 'index.html' %}
{% load static %}

{% block main %} 

	<br>
	<form method="post" class="form-horizontal">
		{% csrf_token %}

		{% for hiddden in form.hidden_fields %}
			{{ hidden }}
		{% endfor %}

		<div class="form-group">
			<label for="{{ form.nombre.id_for_label }}" 
					class="col-sm-2 control-label">{{ form.nombre.label }}</label>
			<div class="col-sm-8">{{ form.nombre }} </div>
		</div>
		<div class="form-group">
			<label for="{{ form.apellido.id_for_label }}" 
					class="col-sm-2 control-label">{{ form.apellido.label }}</label>
			<div class="col-sm-8">{{ form.apellido }}</div>
		</div>
		<div class="form-group">
			<label for="{{ form.email.id_for_label }}" 
					class="col-sm-2 control-label">{{ form.email.label }}</label>
			<div class="col-sm-8">{{ form.email }}</div>
		</div>
		<div class="form-group">
			<label for="{{ form.password.id_for_label}}" 
					class="col-sm-2 control-label">{{ form.password.label }}</label>
			<div class="col-sm-8">{{ form.password }}</div>
		</div>
		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-8">
				<input class="btn btn-primary pull-right" type="submit" name="submit" value="Registrarse">
			</div>
		</div>
	</form>		

{% endblock %}

WebScraping/templates/buscar_repositorio.html
{% extends 'index.html' %}
{% load static %}

{% block form %}

<div class="br-search">
     <form action="/index/" method="get">
            <div id="ctn-bar-search">
                <input type="text" id="inputSearch" name="git" placeholder="¿Qué deseas buscar?">
                <input type="submit" value="Buscar">
            </div>
     </form>
</div>
{% endblock %}

WebScraping/templates/index_repositorios.html
{% extends 'index.html' %}
{% load static %}

{% block main %}
    <link href="{% static 'css/index.css' %}" rel="stylesheet" />
	<!--<br>
	<a class="btn btn-primary" href="{% url 'repositorios:create_user' %}">Nuevo Usuario</a>-->
	<p align="center" class="text-success fa-2x">Repositorios Scrapeadas</p>
	<div>
		<table class="table-details-git"  border="1">
			<thead>
				<tr>
	                <th>Título</th>
	                <th>Descripción</th>
					<!--<th># Watch</th>-->
					<th>Star</th>
					<th>Fork</th>
					<th>Fecha Creación</th>
					<th>Fecha Actualización</th>
					<th>Commits</th>
					<th>Colaboradores</th>
	                <th>Lenguajes</th>
	                <th>URL Repositorio</th>
	            </tr>
            </thead>
            <tbody>
				{% for item in repositorio %}
				   	<tr>
						<td>{{ item.titulo }}</td>
						<td>{{ item.descripcion }}</td>
						<td>{{ item.star }}</td>
						<td>{{ item.fork }}</td>
						<td>{{ item.fecha_creacion }}</td>
						<td>{{ item.fecha_actualizacion }}</td>
						<!--<td><a href="{{ item.url_commits }}" target="_blank">Ver Commits</a></td>-->
						<td><a href="{{ item.url_commits }}" target="_blank"><center>Ver Commits</center></a></td>

						<td><a href="{{ item.url_colaboradores }}" target="_blank"><center>Ver Colaboradores</center></a></td>
						<td><a href="{{ item.url_lenguajes }}" target="_blank"><center>Ver Lenguajes</center></a></td>
						<td><a href="{{ item.url_repositorio }}" target="_blank"><center>Ver Repositorio</center></a></td>

					</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
{% endblock %}